services:
  ros2_dev:
    container_name: ros2_dev
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=host.docker.internal:0
      - LIBGL_ALWAYS_INDIRECT=1
      - ROS_DOMAIN_ID=42
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/root/workspace/src
      - ./training:/root/workspace/training
    deploy:
      resources:
        reservations:
          memory: 24G
    network_mode: "host"
    tty: true
    stdin_open: true